services:
  - type: web
    name: projetdahiraformulair
    env: node
    region: frankfurt
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: node backend/src/server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        fromDatabase:
          name: dahira-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://projetdahiraformulair.onrender.com

databases:
  - name: dahira-postgres
    databaseName: dahira
    user: dahira_user
    region: frankfurt
    plan: free
    ipAllowList: []
